# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-16 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190816_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date',
        ),
    ]
